### ISSUE TITLE
upload-charm fails when a charm has a newly added resource

### ISSUE THREAD

**Issue by agathanatasha** [canonical/charming-actions#76] opened 2022-11-23 17:36 UTC
### Bug Description

Upload-charm action fails when charm is updated from not having any resources to having a resource. When uploading the resources, charmcraft is verifying resources specification against the latest metadata on charmcraft (which is outdated in this scenario). The new charm needs to be uploaded first before uploading a resource.

### To Reproduce

1. A new charm or a charm with no resources specified previously
2. Add resources specifications in `metadata.yaml`
3. Run upload-charm action

### Environment

On github
[failed github action run for reference](https://github.com/canonical/kratos-operator/actions/runs/3274984359/jobs/5389242447#step:5:53)

### Relevant log output

```shell
/snap/bin/charmcraft upload-resource --quiet kratos oci-image --image 9f4e08abbf6a
Store operation failed:
- resource-not-found: No oci-image type "oci-image" resource found
```

**Comment by ca-scribner** [comment] 2023-06-06 18:16
Duplicate of #58

**Closed by ca-scribner** 2023-06-06 18:16 UTC
Labels: Type: Bug, Status: Triage
